### ISSUE TITLE
make menuconfig 出现错误。

### ISSUE THREAD

**Issue by gswangmd-gssi** [xiaorouji/openwrt-passwall#806]
tmp/.config-package.in:75026:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:75026:	symbol PACKAGE_luci-app-passwall depends on PACKAGE_xray
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:99868:	symbol PACKAGE_xray is selected by PACKAGE_luci-app-passwall

**Comment by Mattraks** [comment]
**Due to the addition of the parameter PROVIDES in xray, the dependency check is repeated, which can be ignored without affecting the compilation. 
If you want to solve the prompt, you can delete the v2ray package, or delete this parameter**


define Package/$(PKG_NAME)
  TITLE:=A platform for building proxies
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Project X
  DEPENDS:=$(GO_ARCH_DEPENDS) +ca-certificates
  **PROVIDES:=v2ray**
endef
